include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: false
    strict-inference: true
    strict-raw-types: true
  errors:
    # This turns inference failures into hard errors
    todo: ignore 
    argument_type_not_assignable: error

linter:
  rules:
    # --- ERROR PRONE RULES ---
    - avoid_slow_async_io
    - no_duplicate_case_values
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - test_types_in_equals
    - valid_regexps

    # --- THE RULE FOR DYNAMIC ---
    - avoid_annotating_with_dynamic

    # --- STYLE & ARCHITECTURE ---
    - always_use_package_imports
    - avoid_void_async
    - directives_ordering
    - omit_local_variable_types
    - prefer_final_locals
    - prefer_interpolation_to_compose_strings
    - unawaited_futures
    - prefer_collection_literals
    - type_annotate_public_apis

    # --- FLUTTER SPECIFIC ---
    - avoid_unnecessary_containers
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - sized_box_for_whitespace
    - use_key_in_widget_constructors
